### PR TITLE
Fix for 'EnableRegionalDisco' is disabled (deprecation of the regional discovery service, replaced by global discovery service)

### PR DESCRIPTION
**Pull request by bilal684**
This PR fixes Issue #7 . Issue is caused by the deprecation of the regional discovery service. A simple upgrade of the Microsoft Xrm assemblies fixes the issue.

### CODE REVIEW

**Comment by tsharp** [comment]
Thank you for this PR! I’ll pull these changes and test.

**Comment by bilal684** [comment]
You're welcome! 🙂 Thank you!

**Comment by SteveTe** [comment]
Any updates on release of the latest code?

**Comment by lilclash1090** [comment]
Hi Tsharp, Could you please pull these changes ? Your VS extension is so usefull ! 
(Thank you Bilal684 for the fix)

**Pull request merged**
